export const positiveEmojis = [
    '🔥',
    '💯',
    '⭐',
    '✨',
    '🌟',
    '💪',
    '👑',
    '🏆',
    '🎯',
    '💎',
    '🚀',
    '✅',
    '💅',
    '👏',
    '🙌',
    '🎉',
    '🎊',
    '🌈',
    '💝',
    '💖',
    '🎨',
    '🌺',
    '🦋',
    '🌞',
    '🍀',
    '🎵',
    '💫',
    '🌸',
    '🌻',
];

export const genZExpressions = [
    'bussin',
    'goose',
    'slaps',
    'fire',
    'lit',
    'goated',
    'hits different',
    'based',
    'no cap',
    'periodt',
    'slay',
    'iconic',
    'main character',
    'understood the assignment',
    'vibe',
    'clean',
    'fresh',
    'valid',
    'hits',
    'W',
    'dub',
    'sheesh',
    'lowkey',
    'highkey',
    'ate',
    'snapped',
    'tea',
    'giving',
    'main',
    'energy',
    'blessed',
    'goals',
    'flex',
    'drip',
    'hits hard',
    'immaculate',
    'vibing',
    'pop off',
    'queen',
    'king',
    'legend',
];

export const expressions = [...positiveEmojis, ...genZExpressions];

export const scores = ['+1', '+2', '+3', '+4', '+5', '+6', '+7', '+8', '+9', '+10'];

export const positiveItalianExpressions = [
    'bene',
    'molto bene',
    'ottimo',
    'fantastico',
    'eccellente',
    'bellissimo',
    'perfetto',
    'magnifico',
    'stupendo',
    'meraviglioso',
    'splendido',
    'incredibile',
    'favoloso',
    'straordinario',
    'eccezionale',
];

export const ItalianEmojis = ['🍋', '🛵', '🍕', '🍇', '🌴', '🏛️', '🍝', '🍷', '🌊', '🧀', '🫒', '🍊'];
